---
- name: Creating CICD Example project
  hosts: localhost
  tasks:
    - name: Creating project...
      shell: |
        oc login -u andrew -p r3dh4t1!
        oc new-project cicd-dev
        oc new-app jenkins-persistent
      register: ocresults
    - debug: 
        var: ocresults.stdout
    - name: Pausing for 30 seconds so project can build. Then getting route.
      pause:
        seconds: 30
    - name: Show PVC attached
      shell: oc get pvc
      register: pvcresults
    - debug:
        var: pvcresults.stdout
    - name: Displaying route. Copy this URL into your browser!
      shell: oc get route | awk 'NR>1 {print $2}'
      register: url
    - debug:
        msg: "Copy and paste this URL to your browser to test: {{ url.stdout }}"