---
- name: Generate Inventory Hosts file
  hosts: localhost
  tasks:
    - name: Move existing hosts file if it exists
      stat: 
        path: /etc/ansible/hosts
      register: hosts_file
    - name: Move hosts file for backup
      shell: mv /etc/ansible/hosts /etc/ansible/hosts.bak
      when: hosts_file.exists
    - name: Create new hosts file
      copy:
        src: ../files/hosts
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: 0644
    - name: Get current GUID
      shell: hostname|awk -F. '{print $2}'
      register: guid
    - name: Print GUID
      debug:
        var: guid.stdout
    - name: Set GUID on hosts file
      replace:
        path: /etc/ansible/hosts
        regexp: 'GUID'
        replace: "{{ guid.stdout  }}"
        backup: yes  
      