---
# - name: Generate Inventory Hosts File
#   hosts: localhost
#   tasks:
#     - name: Generate Inventory script
#       script: /root/ocp_advanced_deployment_homework/scripts/generate_inventory.sh
- name: Generate Inventory Hosts file
  hosts: localhost
  tasks:
    - name: Move existing hosts file if it exists
      shell: mv /etc/ansible/hosts /etc/ansible/hosts.bak
    - name: Create new hosts file
      copy:
        src: ../files/hosts
        dest: /etc/ansible/hosts
        owner: root
        group: root
        mode: 0644
    - name: Get current GUID
      shell: hostname|awk -F. '{print $2}'
      register: guid
    - name: Set GUID on hosts file
      replace:
        path: /etc/ansible/hosts
        regexp: 'GUID'
        replace: guid.stdout
        backup: yes  
      #shell: sed -i "s/GUID/$GUID/g" /etc/ansible/hosts