---
# This play book fires off the installation playbooks for OpenShift.
# See openshift/end-to-end.yml for reference

# Pre-Install Steps
- import_playbook: pre-install.yml

# Install
- import_playbook: install.yml

# Post Install
- import_playbook: post-install.yml