---
- name: Label nodes - Alpha and Beta
  hosts: localhost
  tasks:
    - name: Get current GUID
      shell: hostname|awk -F. '{print $2}'
      register: guid
    - name: Setting logins
      shell: |
        oc login -u amy -p r3dh4t1!
        oc login -u andrew -p r3dh4t1!
        oc login -u brian -p r3dh4t1!
        oc login -u betty -p r3dh4t1!
    - name: Label Alpha and Beta nodes and users
      shell: |
        oc login -u system:admin
        oc label node node1.{{ guid.stdout  }}.internal "client=alpha" --overwrite=true
        oc label node node2.{{ guid.stdout }}.internal "client=beta" --overwrite=true
        oc label node node3.{{ guid.stdout }}.internal "client=common" --overwrite=true
        oc label node node4.{{ guid.stdout }}.internal "client=common" --overwrite=true
        oc label user andrew "client=alpha" --overwrite=true
        oc label user amy "client=alpha" --overwrite=true
        oc label user brian "client=beta" --overwrite=true
        oc label user betty "client=beta" --overwrite=true